exclude: 'Irradiances_ratios/mismatch/martin_ruiz.py|
          Model_comparison/plot_martin_ruiz_mismatch.py'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter on research module.
      - id: ruff-format
        name: ruff-format-research-module
        files: 'research_src/'
        exclude: |
          (?x)^(
            research_src/pvlib_ports/
          )
      # Run the formatter on specific files.
      - id: ruff-format
        name: ruff-format-pvlib-format
        files: |
          (?x)^(
            scripts/plot_martin_ruiz_mismatch.py
          )
        args: [ --line-length 79, --max-line-length 79]
